import Head from "next/head";
import styles from "@/styles/Navbar.module.css";
import { useState, useEffect } from "react";
import { useRouter } from "next/router";
import { useRecoilState, useRecoilValue } from "recoil";
import { userState } from "@/atoms/userAtom";
import { cartProductNumber } from "@/atoms/cartAtom";
import Link from "next/link";

export default function Navbar() {
  const router = useRouter();
  const [user, setUser] = useRecoilState(userState);
  const [notifications, setNotifications] = useState([])
  const cartProductNo = useRecoilValue(cartProductNumber);

  const clickNotification = async(noti)=>{
    // make seen 1
    await fetch('http://localhost:3000/api/notification/'+noti.n_id)

    // move to page
    console.table(noti)
    console.log(noti.t_id)
    router.push('/transaction/' + noti.t_id);
  }

  useEffect(()=>{
    const postData = {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        reciever: localStorage.getItem('email'),
      }),
    }
    const fetchNotifications = async () => {
    try{
        const response = await fetch('http://localhost:3000/api/notification/all',postData)
        const bal = await response.json()
        console.log(bal)
        
        setNotifications(bal)
        
        
    }catch(error){
        console.error('Error fetching noti :', error); 
    }
    }
    fetchNotifications();
},[])


  return (
    <>
      <Head>
        <title>Fashionista</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.navbar}>
        <div className={styles.navbarcontainer}>
          <div className={styles.logo}>
            {/* <img src="https://i.postimg.cc/TP6JjSTt/logo.webp" alt=""/> */}
            <h1 className={styles.brand}>
              Fashionista
              <span style={{ color: "#ff3c78", fontSize: 50 }}>.</span>
            </h1>
          </div>
          <input type="checkbox" name="" id="checkbox" />
          <div className="hamburger-lines">
            <span className="line line1"></span>
            <span className="line line2"></span>
            <span className="line line3"></span>
          </div>
          <ul className={styles.menuitems}>
            {user && (
              <>
                <li>
                  <Link style={{ width: 0, height: 0 }} href="/cart">
                    <img src="/cart.png" alt="" height={25} width={30} />
                    <span className={styles.badgecart}>{cartProductNo}</span>
                  </Link>
                </li>
                <li className={styles.dropdown}>
                  <a href="#" className={styles.dropbtn}>
                    Notification
                    <span className={styles.badge}>{notifications.filter(obj => obj.seen === 0).length}</span>
                  </a>
                <div className={styles.dropdowncontent}>
                  {notifications && notifications.map((item,index)=>(
                    <li key={index} onClick={()=> clickNotification(item)} style={{'backgroundColor': item.seen ===0? "#D3D3D3":"white"}}>{item.message}</li>
                  ))}
                   
                  </div>
                </li>
                <li>
                  <Link href="/home">Home</Link>
                </li>
                <li>
                  <Link href="/profile">Profile</Link>
                </li>
                {/* <li>
                  <Link href="/notification">Notification</Link>
                  <span className={styles.badge}>0</span>
                </li> */}

             

                <li>
                  <a
                    style={{ cursor: "pointer" }}
                    onClick={() => {
                      localStorage.removeItem("user");
                      window.location.href = "/"
                    }}
                  >
                    Logout
                  </a>
                </li>
              </>
            )}

            {!user && (
              <>
                <li>
                  <a href="/login">Login</a>
                </li>
                <li>
                  <a href="/signup">SignUp</a>
                </li>
              </>
            )}
          </ul>
        </div>
      </nav>
    </>
  );
}
